name: "test-local"
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./
        env:
          FOO_VALUE: cat good
          BAR_VALUE: dog food
        with:
          in-file: fixtures/example.yaml.in
          out-file: fixtures/example.yaml

      - run: cat fixtures/example.yaml
